Implement Netim as a domain name provider
upmind/provision-provider-domain-names pull request #92
Opened 2024-07-10 08:24 UTC by netim-com

The following operations are implemented for Netim:

domainAvailabilityCheck()
setAutoRenew()
register()
transfer()
renew()
getInfo()
updateRegistrantContact()
updateNameservers();
setLock()
getEppCode()
poll()

The following operations aren't supported by Netim:
updateIpsTag()

2024-07-10 09:23 UTC, uphlewis commented
![netim_logo](https://github.com/upmind-automation/provision-provider-domain-names/assets/43346009/e1bab8b8-a114-4e6d-8120-fe5826e78063)
![netim_icon](https://github.com/upmind-automation/provision-provider-domain-names/assets/43346009/26846f24-0511-4a68-8c40-873d601840b3)

2024-07-10 09:23 UTC, uphlewis commented
Thanks @netim-com we'll get this reviewed soon and get back to you

2025-01-14 16:31 UTC, RoussKS commented
@netim-com the functionality added via the PR is generally working as expected apart from 2 items

1. `transfer` is not handling the case where the registrant details for the transfer are not provided, a PHP error is thrown
2. `updateRegistrantContact` is not handling the `name` field correctly to split to `firstname` & `lastname`

In terms of coding standards, we use composer for package management, for which there is no need for including files with `require_once "filepath"';` This could be easilly changed if you registered your Rest API package with composer, and hence it could just be required in the `composer.json`, you can see examples in our `composer.json` file -> https://github.com/upmind/provision-provider-domain-names/blob/main/composer.json

Let us know if you have the capacity of doing the suggested changes, otherwise, we can see if we can schedule fixing the issues before merging

2025-01-21 09:27 UTC, netim-com commented
We've just made the corrections for the provider. Note that for the moment, it's not possible for us to use composer, but we'll think about it when we update the API in the future.

2025-01-30 14:59 UTC, RoussKS requested changes
We have made some comments on items that erroring due to invalid namespace, hence throwing php errors for class not found etc.

Apart from that, can you do the minor changes, and we have already reworked major part of the code to follow PHP/PSR standards and also adhere to our codebase requirements.

2025-01-30 14:59 UTC, RoussKS commented on src/Netim/Helper/NetimAPIException.php
> +namespace Upmind\ProvisionProviders\DomainNames\Netim\Helper\Api;
Invalid PSR-4 namespace, it should follow the directory structure and be like `Upmind\ProvisionProviders\DomainNames\Netim\Helper`

2025-01-30 14:59 UTC, RoussKS commented on src/Netim/Helper/APIRest.php
> +namespace Upmind\ProvisionProviders\DomainNames\Netim\Helper\Api;
Invalid PSR-4 namespace, it should follow the directory structure and be like `Upmind\ProvisionProviders\DomainNames\Netim\Helper`

2025-01-30 14:59 UTC, RoussKS commented on src/Netim/Helper/APIRest.php
> +use Upmind\ProvisionProviders\DomainNames\Netim\Helper\Api\NetimAPIException as NetimAPIException;
once namespace is resolved, this like is redundant

2025-01-31 08:17 UTC, netim-com commented on src/Example/Provider.php
> +use Carbon\Carbon;N
Completed

2025-01-31 08:17 UTC, netim-com commented on bin/php-cs-fixer-v3.phar
Yes you can ignore the file permission changes

2025-01-31 08:17 UTC, netim-com commented on fix_formatting.sh
Yes you can ignore the file permission changes

2025-01-31 08:17 UTC, netim-com commented on src/Netim/Helper/NetimAPIException.php
> +namespace Upmind\ProvisionProviders\DomainNames\Netim\Helper\Api;
Done with new commit

2025-01-31 08:18 UTC, netim-com commented on src/Netim/Helper/APIRest.php
> +namespace Upmind\ProvisionProviders\DomainNames\Netim\Helper\Api;
Done with new commit

2025-01-31 08:18 UTC, netim-com commented
New commit done for namespace modifications

2025-01-31 09:03 UTC, RoussKS commented
@netim-com going to merge for now in the feature branch. Apply the coding changes we have ready, and then create a new MR for the main branch

We will tag you to follow the process
Thanks

2025-01-31 09:03 UTC, merged